server:
  port: 8761

#注册中心地址
eureka:
  instance:
    # statusPageUrlPath: ${management.contextPath}/info
    # healthCheckUrlPath: ${management.contextPath}/health
    hostname: 127.0.0.1
  client:
    register-with-eureka: false   #是否注册自己
    fetch-registry: false         #是否检索服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka  #服务注册中心的配置内容，指定服务注册中心的位置
    healthcheck:
       enabled: true                #开启健康检查
  server:
    enableSelfPreservation: true   #关闭自我保护